version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/live_files
hooks:

  ApplicationStart:
    - location: install.sh
      runas: root
  ApplicationStop:
    - location: stop.sh
      runas: root
