version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/live_files
hooks:
  AfterInstall:
    - location: build.sh
      runas: ec2-user
  ApplicationStart:
    - location: install.sh
      runas: root
  ApplicationStop:
    - location: stop.sh
      runas: root
